### PR TITLE
[ray] New ray actor creation model

### LINKED ISSUE #2782: [ray] new worker create model
**Is your feature request related to a problem? Please describe.**
Currently `mars on ray` cluster initialization process is as follows:
* create `RayMainPool` actor for supervisor
* start oscar service for supervisor
* create workers
  * create ray `RayMainPool` actor for worker
  * ray `RayMainPool` actor create `RaySubPool` actors
* start oscar service for workers

This process has some issues:
* When a main pool failed and restarted by ray, it will create new `RaySubPool` actors rather than restart previous `RaySubPool` actors, which makes actor management tricky and not easy to track failed process.
* Currently ray create main pool first, then main pool create subpools. Because `import mars` takes 2~3s, create a worker will take double times.

**Describe the solution you'd like**
It would be better if we can create all ray main/sub pool actors simultaneously, then initialize all mars services in all ray actors. In this way, mars cluster initialization time will be reduced to half of previous. 
At the same time, if a ray main pool failed, all started mainpool and subpools will be the same actors as before.

### PR DESCRIPTION
**Pull request by chaokunyang**
## Related issue number

Fixes #2782 

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://docs.pymars.org/en/latest/development/contributing.html#check-code-styles) for how to run them

### CODE REVIEW

**Comment by qinxuye** [comment]
Could you please try to increase the coverage a bit?

**Comment by qinxuye** [comment]
Branch conflicts, please resolve it.

**Review by qinxuye — APPROVED** [review]
LGTM

**Review by wjsi — APPROVED** [review]
LGTM

**Pull request merged**
