### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by pingrunhuang**
## What do these changes do?

Add dockerfile for building up Mars project runnable environment

## Related issue number
#146

### CODE REVIEW

**Comment by wjsi** [comment]
I wonder whether a Dockerfile like this is necessary, as any user with certain knowledge about docker can build one in a minute, and before you need to use it, you have to remember a lot of arguments in ``docker run``, which is still not convenient for common users. Maybe you need to looking at Dockerfiles written by other projects and rethink how docker can be used to facilitate Mars deployment. What's more, you also need to write documents about how users can use this file. Shall we make automated scripts to build images and upload to DockerHub, or we just add a script for people to build their own image themselves? Adding a Dockerfile is far from enough.

**Comment by pingrunhuang** [comment]
@wjsi As I mentioned in my description, this Dockerfile is just a very basic one. More features should absolutely be added in the future. But this Dockerfile enable us as user to use docker-compose for starting a cluster in a more standard way since in the description of your README file differ from different environment. Therefore, I think it is necessary.

**Comment by wjsi** [comment]
Your comments still cannot convince me as there are multiple ways to run Mars in separate environments, such as virtualenvs and conda envs. Installing in those environments are at least as easy as installing in a docker container.
> ...since in the description of your README file differ from different environment. Therefore, I think it is necessary
I wonder what is the true problem you are encountering, and can you share that with us and let us think how to solve it? As stated above, simply wrapping files in Dockerfile does not solve the problem, but make it more complicated.

**Comment by pingrunhuang** [comment]
@wjsi yeah, sure. I installed it with virtualenv. And after that, running `mars-worker` require me to use `sudo` for higher privilege. Therefore I created one for myself and think might be also helpful for others. But it is totally understandable if you don't accept my solution. Personally I like the light way of creating a cluster for testing and development with docker swarm.

**Comment by wjsi** [comment]
@pingrunhuang Can you open a new issue and paste the error log when you are not run mars-worker with ``sudo``? We can try to solve it.

**Comment by chineking** [comment]
In my opinion, dockerfile is necessary, but how it should be needs further discussion.

**Comment by wjsi** [comment]
Close this as we won't introduce premature changes hacking on fixed issues.

**Pull request closed without merging**
