### PR TITLE
Fix errors when calling where() on reshape results

### LINKED ISSUE #2009: Execution error  zmc1_h_21 = mt.where(self.high_array >= 21, 1, 0).execute()
The execution reported the following error, I don’t know what caused it 
error:
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### PR DESCRIPTION
**Pull request by wjsi**
## What do these changes do?

This PR does things below:

1. Fix TypeError caused by `None`s in shapes
2. Fix shape inconsistency when x and y in `where` are all scalars
3. Fix CI failure for kubernetes

## Related issue number

Fixes #2009

### CODE REVIEW

**Review by hekaisheng — APPROVED** [review]
LGTM

**Comment by shizhiqiang007** [comment]
> ## What do these changes do?
> This PR does things below:
> 
> 1. Fix TypeError caused by `None`s in shapes
> 2. Fix shape inconsistency when x and y in `where` are all scalars
> 3. Fix CI failure for kubernetes
> 
> ## Related issue number
> Fixes #2009

I just tried to run the previous code and found that the problem has not been fixed. Do I have to wait until the next version to update?

import mars.tensor as mt
x = mt.arange(9.).reshape(3, 3)
mt.where(x < 5, 2, -1).execute()

error:TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported type          s according to the casting rule ''safe''

**Comment by qinxuye** [comment]
You need to verify until v0.6.6 released, I will notify in this thread then.

**Comment by qinxuye** [comment]
@shizhiqiang007 v0.6.6 has been released, you can test if issue fixed.

**Pull request merged**
