### PR TITLE
Fix bug that cannot pass numpy array to `mt.swapaxes`

### LINKED ISSUE #1552: [BUG] Cannot pass numpy array into mt.swapaxes
## Describe the bug
I met a bug when i passed numpy array into `mt.swapaxes`. See below:
```
In [35]: p = np.random.rand(3,4,5)                                                                                                                                                                   

In [36]: mt.swapaxes(p, 0, -1)                                                                                                                                                                       
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-016cb9916fdb> in <module>
----> 1 mt.swapaxes(p, 0, -1)

~/anaconda3/envs/pymars0.6/lib/python3.7/site-packages/mars/tensor/base/swapaxes.py in swapaxes(a, axis1, axis2)
    150         return a
    151 
--> 152     op = TensorSwapAxes(axis1, axis2, dtype=a.dtype, sparse=a.issparse())
    153     return op(a)

AttributeError: 'numpy.ndarray' object has no attribute 'issparse'
```

### PR DESCRIPTION
**Pull request by YoshieraHuang**
## What do these changes do?

Fix cannot pass numpy array into mt.swapaxes

## Related issue number

Fixes #1552

### CODE REVIEW

**Comment by YoshieraHuang** [comment]
I fix the bug and align the imports in the alphabet order.

**Comment by qinxuye** [comment]
Could you add a test to `testSwapaxesExecution` please?

**Comment by YoshieraHuang** [comment]
> Could you add a test to `testSwapaxesExecution` please?

i issued a new commit for adding testing

**Comment by YoshieraHuang** [comment]
The etcd parts failed for python3.8

**Comment by qinxuye** [comment]
> The etcd parts failed for python3.8

I have restarted CI.

**Review by qinxuye — APPROVED** [review]
LGTM

**Pull request merged**
