### PR TITLE
Fix minikube installation

### PR DESCRIPTION
**Pull request by hekaisheng**
## What do these changes do?

Follow the documentation(https://minikube.sigs.k8s.io/docs/tutorials/setup_minikube_in_github_actions/) to fix the minikube setup in CI.

## Related issue number

Fixes #xxxx

## Check code requirements

- [x] tests added / passed (if needed)
- [x] Ensure all linting tests pass, see [here](https://docs.pymars.org/en/latest/development/contributing.html#check-code-styles) for how to run them

### CODE REVIEW

**Review by fyrestone — APPROVED** [review]

**Comment by chaokunyang** [comment]
Some CI seems run repeatly with this PR:
image

Before this PR, CI only runs 24 checks, but 40 checks are running in this PR.

**Comment by hekaisheng** [comment]
Convert to draft as #3205 make kubernetes tests broken, waiting the fix.

**Comment by hekaisheng** [comment]
As #3254 fixes k8s tests, this PR can be merged if CI is green.

**Review by zhongchun — APPROVED** [review]
LGTM.

**Review by fyrestone — APPROVED** [review]
LGTM

**Pull request merged**
