### PR TITLE
Add metrics docs

### PR DESCRIPTION
**Pull request by zhongchun**
## What do these changes do?
Add metrics docs including:
* How to use metrics
* Metrics backend
* Metrics naming convention

## Related issue number

Fixes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://docs.pymars.org/en/latest/development/contributing.html#check-code-styles) for how to run them

### CODE REVIEW

**Comment by qinxuye** [comment]
Refer this doc: https://docs.pymars.org/zh_CN/latest/development/contributing.html#building-documentations to add translation.

**Comment by zhongchun** [comment]
> Refer this doc: https://docs.pymars.org/zh_CN/latest/development/contributing.html#building-documentations to add translation.

Ok, thanks for you reminder.

**Review by qinxuye — APPROVED** [review]
LGTM

**Review by wjsi — APPROVED** [review]
LGTM

**Pull request merged**
