### PR TITLE
Optimize serializable memory

### PR DESCRIPTION
**Pull request by fyrestone**
## What do these changes do?

This PR implements the serializable fields by slots instead of a value dict, 

- Reduces **~25%** memory usage / peaks of constructing graph (in the supervisor).
- Reduces **~40%** memory footprint of serializables (most of them are chunks). 
- About **~12%** faster when serialize / deserialize the serializables.

Test code 
``` python
import time
import tracemalloc
import mars.dataframe as md
import mars.tensor as mt
from mars.core.graph import TileableGraph, TileableGraphBuilder, ChunkGraphBuilder
from asv.extern import asizeof

tracemalloc.start()
start_time = time.time()

num_rows = 10000
df1 = md.DataFrame(
    mt.random.rand(num_rows, 4, chunk_size=10), columns=list("abcd")
)
df2 = md.DataFrame(
    mt.random.rand(num_rows, 4, chunk_size=10), columns=list("abcd")
)
merged_df = df1.merge(
    df2, left_on="a", right_on="a", auto_merge="none", bloom_filter=False
)
graph = TileableGraph([merged_df.data])
next(TileableGraphBuilder(graph).build())
chunk_graph = next(ChunkGraphBuilder(graph, fuse_enabled=False).build())
duration = time.time() - start_time
print(f"Chunk graph size: {len(chunk_graph)}")

size, peak = tracemalloc.get_traced_memory()
sizeof_chunk_graph = asizeof.asizeof(chunk_graph)
print(f"{sizeof_chunk_graph=}, {size=}, {peak=}, {duration=}")
```

Before this PR:
```
Chunk graph size: 9001
sizeof_chunk_graph=25969144, size=39536890, peak=41326016, duration=3.821443796157837
```

With this PR:
```
Chunk graph size: 9001
sizeof_chunk_graph=15783832, size=28084948, peak=29874137, duration=3.8508338928222656
```

## Related issue number

Fixes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://docs.pymars.org/en/latest/development/contributing.html#check-code-styles) for how to run them

### CODE REVIEW

**Comment by wjsi** [comment]
How about the speed using one namedtuple for one Serializable class and construct namedtuples with NTSerializable(**kw)? That could possibly be faster than getters and setters when constructing Serializable instances.

**Comment by qinxuye** [comment]
Could you please add a asv bench which benches the memory/peak memory usage of serialization? Maybe add a memory test to exist tests.

**Comment by fyrestone** [comment]
> How about the speed using one namedtuple for one Serializable class and construct namedtuples with `NTSerializable(**kw)`? That could possibly be faster than getters and setters when constructing Serializable instances.

Good suggestion. Let me try some optimizations.

**Comment by fyrestone** [comment]
> Could you please add a asv bench which benches the memory/peak memory usage of serialization? Maybe add a memory test to exist tests.

Sure. I will add a asv bench after the PR is optimized.

**Pull request merged**
