### PR TITLE
[ENH] Enrich `nvutils.py` for GPU/CUDA initialization

### PR DESCRIPTION
**Pull request by dlee992**
CP one commit from xprobe-inc/mars, for enhancing GPU-related utils.

After merging this, I would open another PR, coming from xprobe-inc/xorbits, to fix a series of similar issues. 

All credits in this PR belong to xprobe-inc.

### CODE REVIEW

**Review by fyrestone — APPROVED** [review]
LGTM

**Comment by qinxuye** [comment]
Oh, we should do this, anyway, thanks.

**Comment by qinxuye** [comment]
https://github.com/xprobe-inc/xorbits/pull/242

This PR is helpful to address #3325 .

**Comment by dlee992** [comment]
> [xprobe-inc/xorbits#242](https://github.com/xprobe-inc/xorbits/pull/242)
> 
> This PR is helpful to address #3325 .

Thanks, xuye! I have added related code in #3337.

**Pull request merged**
