### PR TITLE
Add _binary_roc_auc_score method

### LINKED ISSUE #2402: Implement `_binary_roc_auc_score`
**Is your feature request related to a problem? Please describe.**
Implement the analogous function for **sklearn** **`_binary_roc_auc_score`**

### PR DESCRIPTION
**Pull request by Divyanshu-Singh-Chauhan**
## What do these changes do?
Contains a utility function similar to **sklearn  _binary_roc_auc_score**. 
The function will be used for building the general **`sklearn.metrics.roc_auc_score`** functionality.
The code format and documentation are kept similar to the **sklearn** function. 

## Related issue number
Fixes #2402

### CODE REVIEW

**Comment by qinxuye** [comment]
Unittest is absent, try to add some tests to ensure coverage, thanks in advance.

**Comment by qinxuye** [comment]
Some suggestion, in order to test this sole function, we can generate some data maybe random one, and test if the result of this function equals sklearn one.

**Comment by qinxuye** [comment]
Do you get stuck in some tricky part, if so, feel free to reach out to us.

**Comment by Divyanshu-Singh-Chauhan** [comment]
> Do you get stuck in some tricky part? if so, feel free to reach out to us.



> Unittest is absent, try to add some tests to ensure coverage, thanks in advance.

Yes, will do that in recent days.
Still, I compared this function locally, and worked correctly. 
I'll do some more checks

**Comment by Divyanshu-Singh-Chauhan** [comment]
> Some suggestion, in order to test this sole function, we can generate some data maybe random one, and test if the result of this function equals sklearn one.

Tested the function with more randomly generated values and the function is giving exact results as that of sklean's function.
Attaching the screenshot of both.

1. **`Mars _binary_roc_auc_curve`**
mars_binary
---------------------------------------------------------------------
2. **`Sklearn's _binary_roc_auc_curve`**
sklearn_binary

**Comment by qinxuye** [comment]
Great, however,  for an sophisticated project, unittest is very important, it can ensure that with the time going, the function can work still as expected.

You can refer to 

https://github.com/mars-project/mars/blob/0e1171467e8d67fb4a15239550cf313ec1f2e8a5/mars/learn/neighbors/tests/test_nearest_neighbors.py#L268-L316

This function creates some data, and compare the result of Mars and sklearn to ensure the correctness.

You can add test to `metrics/tests/test_ranking.py`.

**Comment by Divyanshu-Singh-Chauhan** [comment]
Yes sure. I have the unittest ready with me but, `_binary_roc_auc_score` is a **private** function in the sklearn framework thus I had it tested explicitly from Sklearn's code documentation. 
Thus, for an 'open' unittest, it wouldn't be possible to import the function from sklearn and use it in the code for comparison.

**Comment by qinxuye** [comment]
> Thus, for an 'open' unittest, it wouldn't be possible to import the function from sklearn and use it in the code for comparison.

You are right, for now, I think two solutions.

1. We import the private function from sklearn, and test it for now, later, when we finish implementing `roc_auc_score`, remove the temp code.
2. We just implement the `roc_auc_score` and test it.

What's your opinion about that?

**Comment by Divyanshu-Singh-Chauhan** [comment]
> > Thus, for an 'open' unittest, it wouldn't be possible to import the function from sklearn and use it in the code for comparison.
> 
> You are right, for now, I think two solutions.
> 
> 1. We import the private function from sklearn, and test it for now, later, when we finish implementing `roc_auc_score`, remove the temp code.
> 2. We just implement the `roc_auc_score` and test it.
> 
> What's your opinion about that?

Yes, these two are the possible ways to go. 
I think we should stick with the 1st one because for` roc_auc_score` implementation there are at least **2** more private functions needed to implement, so in total **3** more functions needs to be implemented to complete the roc_auc_score function ( if we are following a similar structure to that of its Sklearn's counter). If anyone else also wishes to contribute to this issue then, they can implement the other functions using the "already implemented" private functions. 
I was thinking in this direction.

**Comment by qinxuye** [comment]
OK, you'd prefer 1st option? I think for now, we can simply import the private function from sklearn for test purpose which is truly necessary to catch up coverage, when `roc_auc_score` is fully implemented, we can refine it.

What do you think? how about just commit the test part and let this PR get merged first?

**Comment by Divyanshu-Singh-Chauhan** [comment]
Sure. Seems fine to me. 
I'll add the unittest and import the private function to the branch then.

**Comment by Divyanshu-Singh-Chauhan** [comment]
Added the unittest as discussed.

**Comment by qinxuye** [comment]
> Added the unittest as discussed.

Nice, could you please merge the master branch and resolve conflict?

**Comment by Divyanshu-Singh-Chauhan** [comment]
> > Added the unittest as discussed.
> 
> Nice, could you please merge the master branch and resolve conflict?

Merged and resolved.

**Comment by qinxuye** [comment]
CI failed, could you please fix it?

**Comment by Divyanshu-Singh-Chauhan** [comment]
There are some more failing checks, any idea regarding them?

**Comment by qinxuye** [comment]
I did it for you, quite a few format about flake8, and I added a few exception test to increase coverage, not a big deal, you can check the commit I just push.

**Comment by Divyanshu-Singh-Chauhan** [comment]
> I did it for you, quite a few format about flake8, and I added a few exception test to increase coverage, not a big deal, you can check the commit I just push.

Looks great!
This function now seems correct. 
For remaining "private" functions, they can be opened similarly in new issues I think.

**Review by qinxuye — APPROVED** [review]
LGTM

**Review by wjsi — APPROVED** [review]
LGTM

**Comment by qinxuye** [comment]
Thanks, look forward to seeing more contributions from you.

**Comment by Divyanshu-Singh-Chauhan** [comment]
Sure, glad to contribute!

**Pull request merged**
