### PR TITLE
[ray] refine mars on ray usability

### PR DESCRIPTION
**Pull request by chaokunyang**
## What do these changes do?
Refine mars on ray usability and documents.
### Example1
```python
import mars
import mars.dataframe as md
import mars.tensor as mt
session = mars.new_ray_session(cluster_name='abc', worker_num=2)
mt.random.RandomState(0).rand(1000_0000, 5, chunk_size=100_0000).sum().execute()
df = md.DataFrame(
    mt.random.rand(1000_0000, 4, chunk_size=500_0000),
    columns=list('abcd'))
print(df.sum().execute())
```

### Example2
Create a mars cluster:
```python
import mars.dataframe as md
import mars.tensor as mt
from mars.deploy.oscar import new_cluster_in_ray, new_ray_session
cluster = new_cluster_in_ray(cluster_name='test', worker_num=2)
```
then connect it in the client:
```python
session = new_ray_session(address = cluster.address)
```

## Related issue number
#2112 

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://docs.pymars.org/en/latest/development/contributing.html#check-code-styles) for how to run them

### CODE REVIEW

**Comment by wjsi** [comment]
Please remove unused imports according to messages by flake 8 (https://dev.azure.com/mars-project/mars/_build/results?buildId=1934&view=logs&jobId=435ca956-9126-505f-566f-fff31072e2ba&j=435ca956-9126-505f-566f-fff31072e2ba&t=456eced4-5f9f-56bd-1d85-873f530e72f3).

**Comment by chaokunyang** [comment]
image

**Review by wjsi — APPROVED** [review]
LGTM

**Review by qinxuye — APPROVED** [review]
LGTM

**Pull request merged**
