### PR TITLE
To vineyard: avoid copy when chunks are already in vineyard (vineyard is the backend).

### PR DESCRIPTION
**Pull request by sighingnow**
## What do these changes do?

+ Avoid copy chunks again when they are already in vineyard.
+ Use latest released vineyard in CI, rather than a hacked one.

## Related issue number

N/A

### CODE REVIEW

**Comment by sighingnow** [comment]
The coverage missing for diff looks OK, since we doesn't test such case for non-distributed/clustered testing. This PR added two extra cases that has already covered some uncovered branches.

**Review by qinxuye — APPROVED** [review]
LGTM

**Review by wjsi — APPROVED** [review]
LGTM

**Comment by sighingnow** [comment]
Thank for merging!

**Pull request merged**
