### PR TITLE
fix remove mapper data

### LINKED ISSUE #3213: [BUG] Mars shuffle AttributeError: 'mars.oscar.core.ActorRef' object has no attribute '_remove_mapper_data'
**Describe the bug**
When running mars shuffle, mars will invoke `_remove_mapper_data` to clean data, but the call throws `AttributeError: 
 mars.oscar.core.ActorRef' object has no attribute '_remove_mapper_data'`
**To Reproduce**
To help us reproducing this bug, please provide information below:
1. Your Python version:3.8.13
2. The version of Mars you use:master
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
```
mars/deploy/oscar/tests/test_local.py:344: in test_execute_describe
    await info
mars/deploy/oscar/session.py:105: in wait
    return await self._aio_task
mars/deploy/oscar/session.py:953: in _run_in_background
    raise task_result.error.with_traceback(task_result.traceback)
mars/services/task/supervisor/processor.py:369: in run
    await self._process_stage_chunk_graph(*stage_args)
mars/services/task/supervisor/processor.py:247: in _process_stage_chunk_graph
    chunk_to_result = await self._executor.execute_subtask_graph(
mars/services/task/execution/mars/executor.py:196: in execute_subtask_graph
    return await stage_processor.run()
mars/services/task/execution/mars/stage.py:231: in run
    return await self._run()
mars/services/task/execution/mars/stage.py:251: in _run
    raise self.result.error.with_traceback(self.result.traceback)
mars/services/scheduling/worker/execution.py:396: in internal_run_subtask
    await self.ref()._remove_mapper_data.tell(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   return object.__getattribute__(self, item)
E   AttributeError: 'mars.oscar.core.ActorRef' object has no attribute '_remove_mapper_data'

mars/oscar/core.pyx:123: AttributeError

```
5. Minimized code to reproduce the error.
`pytest -v -s  mars/deploy/oscar/tests/test_local.py::test_execute_describe`
**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by chaokunyang**
## What do these changes do?
This PR fix `AttributeError: 'mars.oscar.core.ActorRef' object has no attribute '_remove_mapper_data'`

## Related issue number

Fixes #3213 

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://docs.pymars.org/en/latest/development/contributing.html#check-code-styles) for how to run them

### CODE REVIEW

**Comment by fyrestone** [comment]
Can you add some tests for it?

**Review by zhongchun — APPROVED** [review]
LGTM.

**Comment by chaokunyang** [comment]
> Can you add some tests for it?

We already have UT for such cases, but previous CI script ignore such error. This PR fixed it by `set -e` in bash

**Review by fyrestone — APPROVED** [review]
LGTM

**Pull request merged**
