### PR TITLE
Add `get_cluster_info` method for ClusterAPI

### PR DESCRIPTION
**Pull request by zhongchun**
## What do these changes do?
There is no method to get worker node resources when you want to know the resources in the cluster. Especially when mars on ray, there is some confuse. Because we have a `RayActorDriver` which keeps initialized cluster info, but when we use `ClusterStateActor` to request or release worker, cluster info will change.  

So we should maintain cluster info like worker node resources in one place and ClusterAPI is just appropriate.

## Check code requirements

- [x] tests added / passed (if needed)
- [x] Ensure all linting tests pass, see [here](https://docs.pymars.org/en/latest/development/contributing.html#check-code-styles) for how to run them

### CODE REVIEW

**Comment by hekaisheng** [comment]
Could you add some cases to cover your code?

**Comment by zhongchun** [comment]
> Could you add some cases to cover your code?

Ok.

**Comment by hekaisheng** [comment]
This PR seems only for Ray backend, could you add the implementation for default backend?

**Comment by zhongchun** [comment]
> This PR seems only for Ray backend, could you add the implementation for default backend?

How about  implement it in later pr? I opens an issue https://github.com/mars-project/mars/issues/2617 and I will implement it in the near future.

**Pull request closed without merging**
