### PR TITLE
Change code owners to Mars PMC maintainers

### PR DESCRIPTION
**Pull request by qinxuye**
## What do these changes do?

This PR changed code owners to Mars PMC maintainers.

## Related issue number

Fixes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://docs.pymars.org/en/latest/development/contributing.html#check-code-styles) for how to run them

### CODE REVIEW

**Review by hekaisheng — APPROVED** [review]
LGTM

**Comment by qinxuye** [comment]
This PR did not touch code modification, thus skip CI.

**Review by chaokunyang — APPROVED** [review]
LGTM

**Comment by wjsi** [comment]
For specific modules, code owners can act as a mechanism for notification. Thus it might not be appropriate to remove all owners.

**Pull request merged**
