### PR TITLE
[Shuffle] Add `n_mappers` and `n_reducers` to `ShuffleProxy`

### PR DESCRIPTION
**Pull request by chaokunyang**
## What do these changes do?
- add `n_mappers/n_reducers` info to shuffle proxy, so it can be used for shuffle optimization such as fetch by index.
- Refine `n_reducers`/`reducer_ordinal` by set those attributes in `MapReduceOperand#new_chunks`

## Related issue number

Fixes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://docs.pymars.org/en/latest/development/contributing.html#check-code-styles) for how to run them

### CODE REVIEW

**Comment by wjsi** [comment]
In my opinion, `n_mappers` and `n_reducer` shall be recorded on graph execution to reduce complexity for operand writers.

**Comment by chaokunyang** [comment]
> In my opinion, `n_mappers` and `n_reducer` shall be recorded on graph execution to reduce complexity for operand writers.

Some reducer chunks are not included in the chunk graph, we can't get all info when build graph.

**Review by wjsi — APPROVED** [review]
LGTM

**Review by zhongchun — APPROVED** [review]
LGTM.

**Pull request merged**
